---
sudo: required
osx_image: xcode9.3

before_install:
  # Uninstall existing Homebrew installation.
  #- curl -sLO https://raw.githubusercontent.com/Homebrew/install/master/uninstall
  #- chmod +x ./uninstall
  #- ./uninstall --force
  - sudo rm -rf /usr/local/Homebrew
  - sudo rm -rf /usr/local/Caskroom
  - sudo rm -rf /usr/local/bin/brew

install:
  # Install pip.
  - sudo easy_install pip

  # Install Ansible.
  - sudo pip install ansible
  
  # Check the role/playbook's syntax.
  - "ansible-playbook byansible/playbooks/main.yml --syntax-check"

  # Test the playbook.
  - "travis_wait 30 ansible-playbook -i byansible/hosts byansible/playbooks/main.yml" -vvv