---
- name: install packages
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Run Homebrew & Cask install script
      include_role:
        name: homebrew-install
    
    - name: Install Web Browsers
      include_role:
        name: webbrowser-install
    
    - name: Install Text Editors
      include_role:
        name: text-editor-install

